### ISSUE TITLE
!error: symbolic links are missing

### ISSUE THREAD

**Issue by worthless443** [bobwya/opengl.eselect#2]
Put `opengl.eselect` in `eselect/modules` dir, and running `eselect opengl list` complains with this
```
!!! Error: Invalid symbolic links: OpenGL implementation "" symbolic links are missing.
Available OpenGL implementations:
  (none found)
exiting

```
any way to fix this?

**Comment by bobwya** [comment]
This repository is no longer required... **media-libs/libglvnd** replaced this eselect switching utility months ago...

See: [gentoo discussion forums: portage forces USE="libglvnd"](https://forums.gentoo.org/viewtopic-t-1117480-start-0.html)

See: [glvnd/libglvnd](https://gitlab.freedesktop.org/glvnd/libglvnd)
